Product.create!([
  {name: "Nike Air Monarch", price: "105.0", image_url: "https://deichmann.scene7.com/asset/deichmann/US_01_750193_00?$rr_main$&defaultImage=default_obs", description: "The ultimate lifestyle shoe", stock: true},
  {name: "Nike Kyrie Irving Signature", price: "120.0", image_url: "https://kickz.akamaized.net/se/media/images/p/600/nike-KYRIE_5-BLACK_WHITE_BRIGHT_CRIMSON_AMARILLO-1.jpg", description: "A basketball that's just really swell", stock: true},
  {name: "Adidas Yeesus Moon Boots", price: "250.0", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyhkoIkBRJRIcaKSh9xxXGOr9AhlceA-4neHbPsYk503IN_rzs5A&s", description: "An absolutely hideous lifestyle shoe. Honestly, who would wear these?", stock: true},
  {name: "Adidas Dame 6", price: "120.0", image_url: "https://dks.scene7.com/is/image/dkscdn/19ADIMDM6BLKRD112MNS_Black_Red_is?wid=685&fmt=jpg", description: "A fine looking shoe, great for basketball players of all ages and skill levels", stock: true},
  {name: "Adidas Classic Lifestyle", price: "85.0", image_url: "https://images.complex.com/complex/image/upload/w_680/t_in_content_image/reebok-club-c-85-vintage-020_o1u4yg.jpg", description: "A classic sneaker. They look great fresh but look even better when they feel a little lived in, IMHO", stock: true},
  {name: "Reebok makes a basketball shoe", price: "50.0", image_url: "https://i.frog.ink/2tovqjCC/2274493005882-0_600.jpg?v=1548097133.153", description: "As the name states, Reebok makes a basketball shoe. These ridiculously large hi-tops will even have people with small feet wondering if they'll have room in their gym bag to store these puppies", stock: true},
  {name: "New Balance Lifestyle", price: "85.0", image_url: "https://scene7.zumiez.com/is/image/zumiez/Zoom_PDP/New-Balance-Lifestyle-997H-Grey-%26-Navy-Shoes-_319504-front-US.jpg", description: "mellow look, elite cushion", stock: true},
  {name: "Classic Crocs", price: "30.0", image_url: "https://dks.scene7.com/is/image/dkscdn/19CCSACLSSCMRCNFLFOT_Red_White_Blue_is?wid=685&fmt=jpg", description: "Ultimate Lounge Wear", stock: true}
])
